name: rocket league
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Buildozer Action
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer -v android debug
